### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by mrivas-reyes**

### CODE REVIEW

**Comment by krishvoor** [comment]
@mrivas-reyes - Please add description to this PR, to get more context.
@dpkshetty - Can you review the PR ?

**Comment by dpkshetty** [comment]
What is the need for this patch ? I left it at v1.0 as it is used as part of a tutorial

**Comment by dpkshetty** [comment]
@krishvoor @mrivas-reyes see above ^^

**Comment by krishvoor** [comment]
@dpkshetty  - Closing this PR, as this isn't needed.

**Pull request closed without merging**
